/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_accueil2 (void)
{
  GtkWidget *accueil2;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button_gestionfoyer_accueil;
  GtkWidget *button_gestionstock_acceuil;
  GtkWidget *button_nutritionniste_accueil;
  GtkWidget *button_inscription_accueil;
  GtkWidget *button_gestioncapteur_accueil;

  accueil2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (accueil2), _("ACCUEIL"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (accueil2), fixed1);

  label1 = gtk_label_new (_("BIENVENUE"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 200, 32);
  gtk_widget_set_size_request (label1, 320, 64);

  button_gestionfoyer_accueil = gtk_button_new_with_mnemonic (_("GESTION DU FOYER"));
  gtk_widget_show (button_gestionfoyer_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_gestionfoyer_accueil, 32, 360);
  gtk_widget_set_size_request (button_gestionfoyer_accueil, 168, 64);

  button_gestionstock_acceuil = gtk_button_new_with_mnemonic (_("GESTION DU STOCK"));
  gtk_widget_show (button_gestionstock_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_gestionstock_acceuil, 24, 176);
  gtk_widget_set_size_request (button_gestionstock_acceuil, 160, 64);

  button_nutritionniste_accueil = gtk_button_new_with_mnemonic (_("NUTRITIONISTE"));
  gtk_widget_show (button_nutritionniste_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_nutritionniste_accueil, 512, 176);
  gtk_widget_set_size_request (button_nutritionniste_accueil, 200, 64);

  button_inscription_accueil = gtk_button_new_with_mnemonic (_("INSCRIPTION/LOGIN"));
  gtk_widget_show (button_inscription_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_inscription_accueil, 256, 256);
  gtk_widget_set_size_request (button_inscription_accueil, 200, 72);

  button_gestioncapteur_accueil = gtk_button_new_with_mnemonic (_("GESTION DES CAPTEURS"));
  gtk_widget_show (button_gestioncapteur_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_gestioncapteur_accueil, 512, 360);
  gtk_widget_set_size_request (button_gestioncapteur_accueil, 192, 64);

  g_signal_connect ((gpointer) button_gestionfoyer_accueil, "clicked",
                    G_CALLBACK (on_button_gestionfoyer_accueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gestionstock_acceuil, "clicked",
                    G_CALLBACK (on_button_gestionstock_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_nutritionniste_accueil, "clicked",
                    G_CALLBACK (on_button_nutritionniste_accueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_inscription_accueil, "clicked",
                    G_CALLBACK (on_button_inscription_accueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gestioncapteur_accueil, "clicked",
                    G_CALLBACK (on_button_gestioncapteur_accueil_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (accueil2, accueil2, "accueil2");
  GLADE_HOOKUP_OBJECT (accueil2, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (accueil2, label1, "label1");
  GLADE_HOOKUP_OBJECT (accueil2, button_gestionfoyer_accueil, "button_gestionfoyer_accueil");
  GLADE_HOOKUP_OBJECT (accueil2, button_gestionstock_acceuil, "button_gestionstock_acceuil");
  GLADE_HOOKUP_OBJECT (accueil2, button_nutritionniste_accueil, "button_nutritionniste_accueil");
  GLADE_HOOKUP_OBJECT (accueil2, button_inscription_accueil, "button_inscription_accueil");
  GLADE_HOOKUP_OBJECT (accueil2, button_gestioncapteur_accueil, "button_gestioncapteur_accueil");

  return accueil2;
}

GtkWidget*
create_connexion (void)
{
  GtkWidget *connexion;
  GtkWidget *fixed2;
  GtkWidget *label2;
  GtkWidget *entry1_login_connexion;
  GtkWidget *labellogin_connexion;
  GtkWidget *label_password_connexion;
  GtkWidget *entry_password_connexion;
  GtkWidget *button_retour_to_accueil_de_connexion;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *label_outputdeconnexion;
  GtkWidget *button_connexion_alterne;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label12;

  connexion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (connexion), _("CONNEXION"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (connexion), fixed2);

  label2 = gtk_label_new (_("Bienvenue \303\240 l'espace connexion"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 216, 0);
  gtk_widget_set_size_request (label2, 368, 48);

  entry1_login_connexion = gtk_entry_new ();
  gtk_widget_show (entry1_login_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_login_connexion, 352, 120);
  gtk_widget_set_size_request (entry1_login_connexion, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_login_connexion), 8226);

  labellogin_connexion = gtk_label_new (_("login"));
  gtk_widget_show (labellogin_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), labellogin_connexion, 176, 120);
  gtk_widget_set_size_request (labellogin_connexion, 136, 32);

  label_password_connexion = gtk_label_new (_("Password"));
  gtk_widget_show (label_password_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), label_password_connexion, 192, 200);
  gtk_widget_set_size_request (label_password_connexion, 128, 40);

  entry_password_connexion = gtk_entry_new ();
  gtk_widget_show (entry_password_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_password_connexion, 352, 208);
  gtk_widget_set_size_request (entry_password_connexion, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_password_connexion), 8226);

  button_retour_to_accueil_de_connexion = gtk_button_new ();
  gtk_widget_show (button_retour_to_accueil_de_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retour_to_accueil_de_connexion, 0, 456);
  gtk_widget_set_size_request (button_retour_to_accueil_de_connexion, 272, 80);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_retour_to_accueil_de_connexion), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Retour \303\240 l'accueil"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  label_outputdeconnexion = gtk_label_new ("");
  gtk_widget_show (label_outputdeconnexion);
  gtk_fixed_put (GTK_FIXED (fixed2), label_outputdeconnexion, 208, 400);
  gtk_widget_set_size_request (label_outputdeconnexion, 552, 72);

  button_connexion_alterne = gtk_button_new ();
  gtk_widget_show (button_connexion_alterne);
  gtk_fixed_put (GTK_FIXED (fixed2), button_connexion_alterne, 280, 320);
  gtk_widget_set_size_request (button_connexion_alterne, 280, 72);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_connexion_alterne), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("CONNEXION"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_retour_to_accueil_de_connexion, "clicked",
                    G_CALLBACK (on_button_retour_to_accueil_de_connexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_connexion_alterne, "clicked",
                    G_CALLBACK (on_button_connexion_alterne_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (connexion, connexion, "connexion");
  GLADE_HOOKUP_OBJECT (connexion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (connexion, label2, "label2");
  GLADE_HOOKUP_OBJECT (connexion, entry1_login_connexion, "entry1_login_connexion");
  GLADE_HOOKUP_OBJECT (connexion, labellogin_connexion, "labellogin_connexion");
  GLADE_HOOKUP_OBJECT (connexion, label_password_connexion, "label_password_connexion");
  GLADE_HOOKUP_OBJECT (connexion, entry_password_connexion, "entry_password_connexion");
  GLADE_HOOKUP_OBJECT (connexion, button_retour_to_accueil_de_connexion, "button_retour_to_accueil_de_connexion");
  GLADE_HOOKUP_OBJECT (connexion, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (connexion, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (connexion, image3, "image3");
  GLADE_HOOKUP_OBJECT (connexion, label5, "label5");
  GLADE_HOOKUP_OBJECT (connexion, label_outputdeconnexion, "label_outputdeconnexion");
  GLADE_HOOKUP_OBJECT (connexion, button_connexion_alterne, "button_connexion_alterne");
  GLADE_HOOKUP_OBJECT (connexion, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (connexion, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (connexion, image7, "image7");
  GLADE_HOOKUP_OBJECT (connexion, label12, "label12");

  return connexion;
}

GtkWidget*
create_capteur (void)
{
  GtkWidget *capteur;
  GtkWidget *fixed3;
  GtkWidget *label6;
  GtkWidget *button_supprimercapteur_dhia;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label8;
  GtkWidget *button_ajout_capteur_dhia;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *button_retourto_accueil_from_capteur;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label9;

  capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (capteur), _("MENU_CAPTEUR"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (capteur), fixed3);

  label6 = gtk_label_new (_("Bienvenu au menu d'ajout de capteur"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 240, 24);
  gtk_widget_set_size_request (label6, 344, 104);

  button_supprimercapteur_dhia = gtk_button_new ();
  gtk_widget_show (button_supprimercapteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed3), button_supprimercapteur_dhia, 528, 240);
  gtk_widget_set_size_request (button_supprimercapteur_dhia, 224, 64);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_supprimercapteur_dhia), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("SUPPRIMER"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);

  button_ajout_capteur_dhia = gtk_button_new ();
  gtk_widget_show (button_ajout_capteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ajout_capteur_dhia, 80, 232);
  gtk_widget_set_size_request (button_ajout_capteur_dhia, 208, 72);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_ajout_capteur_dhia), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("AJOUTER UN CAPTEUR"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  button_retourto_accueil_from_capteur = gtk_button_new ();
  gtk_widget_show (button_retourto_accueil_from_capteur);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retourto_accueil_from_capteur, 296, 400);
  gtk_widget_set_size_request (button_retourto_accueil_from_capteur, 264, 80);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_retourto_accueil_from_capteur), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retour \303\240 l'acceuil"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox6), label9, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supprimercapteur_dhia, "clicked",
                    G_CALLBACK (on_button_supprimercapteur_dhia_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajout_capteur_dhia, "clicked",
                    G_CALLBACK (on_button_ajout_capteur_dhia_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourto_accueil_from_capteur, "clicked",
                    G_CALLBACK (on_button_retourto_accueil_from_capteur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (capteur, capteur, "capteur");
  GLADE_HOOKUP_OBJECT (capteur, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (capteur, label6, "label6");
  GLADE_HOOKUP_OBJECT (capteur, button_supprimercapteur_dhia, "button_supprimercapteur_dhia");
  GLADE_HOOKUP_OBJECT (capteur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (capteur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (capteur, image5, "image5");
  GLADE_HOOKUP_OBJECT (capteur, label8, "label8");
  GLADE_HOOKUP_OBJECT (capteur, button_ajout_capteur_dhia, "button_ajout_capteur_dhia");
  GLADE_HOOKUP_OBJECT (capteur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (capteur, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (capteur, image4, "image4");
  GLADE_HOOKUP_OBJECT (capteur, label7, "label7");
  GLADE_HOOKUP_OBJECT (capteur, button_retourto_accueil_from_capteur, "button_retourto_accueil_from_capteur");
  GLADE_HOOKUP_OBJECT (capteur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (capteur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (capteur, image6, "image6");
  GLADE_HOOKUP_OBJECT (capteur, label9, "label9");

  return capteur;
}

GtkWidget*
create_accueil0 (void)
{
  GtkWidget *accueil0;
  GtkWidget *fixed4;
  GtkWidget *button_authentification0;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label15;
  GtkWidget *button_incription0;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label14;
  GtkWidget *label_intro;

  accueil0 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (accueil0), _("ACCUEIL0"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (accueil0), fixed4);

  button_authentification0 = gtk_button_new ();
  gtk_widget_show (button_authentification0);
  gtk_fixed_put (GTK_FIXED (fixed4), button_authentification0, 408, 384);
  gtk_widget_set_size_request (button_authentification0, 264, 72);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_authentification0), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("VOUS AVEZ D\303\211JA UN COMPTE?\nCONNECTEZ VOUS !"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox9), label15, FALSE, FALSE, 0);

  button_incription0 = gtk_button_new ();
  gtk_widget_show (button_incription0);
  gtk_fixed_put (GTK_FIXED (fixed4), button_incription0, 8, 384);
  gtk_widget_set_size_request (button_incription0, 280, 72);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_incription0), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("S'INSCRIRE"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);

  label_intro = gtk_label_new (_("BIENVENUE \"INSERT PROJJECT NAME HERE\""));
  gtk_widget_show (label_intro);
  gtk_fixed_put (GTK_FIXED (fixed4), label_intro, 144, 152);
  gtk_widget_set_size_request (label_intro, 416, 104);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (accueil0, accueil0, "accueil0");
  GLADE_HOOKUP_OBJECT (accueil0, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (accueil0, button_authentification0, "button_authentification0");
  GLADE_HOOKUP_OBJECT (accueil0, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (accueil0, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (accueil0, image9, "image9");
  GLADE_HOOKUP_OBJECT (accueil0, label15, "label15");
  GLADE_HOOKUP_OBJECT (accueil0, button_incription0, "button_incription0");
  GLADE_HOOKUP_OBJECT (accueil0, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (accueil0, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (accueil0, image8, "image8");
  GLADE_HOOKUP_OBJECT (accueil0, label14, "label14");
  GLADE_HOOKUP_OBJECT (accueil0, label_intro, "label_intro");

  return accueil0;
}

GtkWidget*
create_window_ajout_capteur_dhia (void)
{
  GtkWidget *window_ajout_capteur_dhia;
  GtkWidget *fixed5;
  GtkWidget *fixed6;
  GtkWidget *image10;
  GtkWidget *entry_nomcapt_dhia;
  GtkWidget *entry_refcapt_dhia;
  GtkWidget *entry_marquecapt_dhia;
  GtkWidget *label16;
  GtkWidget *image11;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *entry_gar_dhia;
  GtkWidget *entry_valmax_dhia;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *entry_valmin_dhia;
  GtkWidget *label23;
  GtkObject *spinbutton_j1_dhia_adj;
  GtkWidget *spinbutton_j1_dhia;
  GtkObject *spinbutton_m1_dhia_adj;
  GtkWidget *spinbutton_m1_dhia;
  GtkObject *spinbutton_a1_dhia_adj;
  GtkWidget *spinbutton_a1_dhia;
  GtkWidget *label24;
  GtkWidget *radiobutton_temp_dhia;
  GSList *radiobutton_temp_dhia_group = NULL;
  GtkWidget *radiobutton_fum__e_dhia;
  GtkWidget *radiobutton_infrarouge_dhia;
  GtkWidget *button_ajoutcapt_interface_dhia;

  window_ajout_capteur_dhia = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_ajout_capteur_dhia), _("Ajout d'un capteur"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window_ajout_capteur_dhia), fixed5);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed6, 224, 112);
  gtk_widget_set_size_request (fixed6, 50, 50);

  image10 = create_pixmap (window_ajout_capteur_dhia, "bob-the-builder-logo-00E9291050-seeklogo.com.png");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed5), image10, 1456, 0);
  gtk_widget_set_size_request (image10, 240, 304);

  entry_nomcapt_dhia = gtk_entry_new ();
  gtk_widget_show (entry_nomcapt_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_nomcapt_dhia, 768, 240);
  gtk_widget_set_size_request (entry_nomcapt_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomcapt_dhia), 8226);

  entry_refcapt_dhia = gtk_entry_new ();
  gtk_widget_show (entry_refcapt_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_refcapt_dhia, 768, 328);
  gtk_widget_set_size_request (entry_refcapt_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_refcapt_dhia), 8226);

  entry_marquecapt_dhia = gtk_entry_new ();
  gtk_widget_show (entry_marquecapt_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_marquecapt_dhia, 768, 368);
  gtk_widget_set_size_request (entry_marquecapt_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_marquecapt_dhia), 8226);

  label16 = gtk_label_new (_("AJOUTER UN CAPTEUR"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 720, 120);
  gtk_widget_set_size_request (label16, 416, 104);

  image11 = create_pixmap (window_ajout_capteur_dhia, "Logo_ESPRIT_-_Tunisie.png");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed5), image11, 0, 0);
  gtk_widget_set_size_request (image11, 680, 248);

  label17 = gtk_label_new (_("REFERENCE"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed5), label17, 576, 336);
  gtk_widget_set_size_request (label17, 88, 16);

  label18 = gtk_label_new (_("MARQUE"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed5), label18, 552, 376);
  gtk_widget_set_size_request (label18, 120, 16);

  label19 = gtk_label_new (_("TYPE DE CAPTEUR"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 568, 416);
  gtk_widget_set_size_request (label19, 144, 25);

  label20 = gtk_label_new (_("GARANTIE"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 544, 472);
  gtk_widget_set_size_request (label20, 144, 32);

  entry_gar_dhia = gtk_entry_new ();
  gtk_widget_show (entry_gar_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_gar_dhia, 768, 472);
  gtk_widget_set_size_request (entry_gar_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_gar_dhia), 8226);

  entry_valmax_dhia = gtk_entry_new ();
  gtk_widget_show (entry_valmax_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_valmax_dhia, 768, 520);
  gtk_widget_set_size_request (entry_valmax_dhia, 56, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmax_dhia), 8226);

  label21 = gtk_label_new (_("VALEUR\nMAXIMALE"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 584, 520);
  gtk_widget_set_size_request (label21, 80, 32);

  label22 = gtk_label_new (_("VALEUR\nMINIMALE"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 576, 560);
  gtk_widget_set_size_request (label22, 88, 48);

  entry_valmin_dhia = gtk_entry_new ();
  gtk_widget_show (entry_valmin_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_valmin_dhia, 768, 568);
  gtk_widget_set_size_request (entry_valmin_dhia, 56, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmin_dhia), 8226);

  label23 = gtk_label_new (_("NOM DU CAPTEUR"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 576, 248);
  gtk_widget_set_size_request (label23, 136, 17);

  spinbutton_j1_dhia_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_j1_dhia = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_j1_dhia_adj), 1, 0);
  gtk_widget_show (spinbutton_j1_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_j1_dhia, 768, 280);
  gtk_widget_set_size_request (spinbutton_j1_dhia, 60, 27);

  spinbutton_m1_dhia_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_m1_dhia = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_m1_dhia_adj), 1, 0);
  gtk_widget_show (spinbutton_m1_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_m1_dhia, 856, 280);
  gtk_widget_set_size_request (spinbutton_m1_dhia, 60, 27);

  spinbutton_a1_dhia_adj = gtk_adjustment_new (1999, 1999, 2050, 1, 10, 10);
  spinbutton_a1_dhia = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_a1_dhia_adj), 1, 0);
  gtk_widget_show (spinbutton_a1_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_a1_dhia, 952, 280);
  gtk_widget_set_size_request (spinbutton_a1_dhia, 60, 27);

  label24 = gtk_label_new (_("DATE"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 584, 288);
  gtk_widget_set_size_request (label24, 80, 16);

  radiobutton_temp_dhia = gtk_radio_button_new_with_mnemonic (NULL, _("DE \nTEMPERATURE"));
  gtk_widget_show (radiobutton_temp_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_temp_dhia, 752, 408);
  gtk_widget_set_size_request (radiobutton_temp_dhia, 128, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_temp_dhia), radiobutton_temp_dhia_group);
  radiobutton_temp_dhia_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_temp_dhia));

  radiobutton_fum__e_dhia = gtk_radio_button_new_with_mnemonic (NULL, _("DE FUM\303\211E"));
  gtk_widget_show (radiobutton_fum__e_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_fum__e_dhia, 904, 416);
  gtk_widget_set_size_request (radiobutton_fum__e_dhia, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_fum__e_dhia), radiobutton_temp_dhia_group);
  radiobutton_temp_dhia_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_fum__e_dhia));

  radiobutton_infrarouge_dhia = gtk_radio_button_new_with_mnemonic (NULL, _("INFRAROUGE\n(DE MOUVEMENT)"));
  gtk_widget_show (radiobutton_infrarouge_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_infrarouge_dhia, 1016, 400);
  gtk_widget_set_size_request (radiobutton_infrarouge_dhia, 152, 56);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_infrarouge_dhia), radiobutton_temp_dhia_group);
  radiobutton_temp_dhia_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_infrarouge_dhia));

  button_ajoutcapt_interface_dhia = gtk_button_new_with_mnemonic (_("CONFIRMER"));
  gtk_widget_show (button_ajoutcapt_interface_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), button_ajoutcapt_interface_dhia, 704, 712);
  gtk_widget_set_size_request (button_ajoutcapt_interface_dhia, 440, 112);

  g_signal_connect ((gpointer) radiobutton_temp_dhia, "toggled",
                    G_CALLBACK (on_radiobutton_temp_dhia_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_fum__e_dhia, "toggled",
                    G_CALLBACK (on_radiobutton_fum__e_dhia_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_infrarouge_dhia, "toggled",
                    G_CALLBACK (on_radiobutton_infrarouge_dhia_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajoutcapt_interface_dhia, "clicked",
                    G_CALLBACK (on_button_ajoutcapt_interface_dhia_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajout_capteur_dhia, window_ajout_capteur_dhia, "window_ajout_capteur_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_nomcapt_dhia, "entry_nomcapt_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_refcapt_dhia, "entry_refcapt_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_marquecapt_dhia, "entry_marquecapt_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label18, "label18");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_gar_dhia, "entry_gar_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_valmax_dhia, "entry_valmax_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label21, "label21");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label22, "label22");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_valmin_dhia, "entry_valmin_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label23, "label23");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, spinbutton_j1_dhia, "spinbutton_j1_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, spinbutton_m1_dhia, "spinbutton_m1_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, spinbutton_a1_dhia, "spinbutton_a1_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label24, "label24");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, radiobutton_temp_dhia, "radiobutton_temp_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, radiobutton_fum__e_dhia, "radiobutton_fum__e_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, radiobutton_infrarouge_dhia, "radiobutton_infrarouge_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, button_ajoutcapt_interface_dhia, "button_ajoutcapt_interface_dhia");

  return window_ajout_capteur_dhia;
}

GtkWidget*
create_window_supprission_capteur_dhia (void)
{
  GtkWidget *window_supprission_capteur_dhia;
  GtkWidget *fixed7;
  GtkWidget *image12;
  GtkWidget *label25;
  GtkWidget *entry_ref_capteur_supprission;
  GtkWidget *button_confirmer_supprission_capteur_dhia;
  GtkWidget *image13;
  GtkWidget *label26;
  GtkWidget *label_output_message_supprission;

  window_supprission_capteur_dhia = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_supprission_capteur_dhia), _("supprission d'un capteur"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window_supprission_capteur_dhia), fixed7);

  image12 = create_pixmap (window_supprission_capteur_dhia, "Logo_ESPRIT_-_Tunisie.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed7), image12, 0, 0);
  gtk_widget_set_size_request (image12, 504, 248);

  label25 = gtk_label_new (_("SUPPRESSION D'UN CAPTEUR"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 792, 168);
  gtk_widget_set_size_request (label25, 360, 96);

  entry_ref_capteur_supprission = gtk_entry_new ();
  gtk_widget_show (entry_ref_capteur_supprission);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_ref_capteur_supprission, 824, 384);
  gtk_widget_set_size_request (entry_ref_capteur_supprission, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ref_capteur_supprission), 8226);

  button_confirmer_supprission_capteur_dhia = gtk_button_new_with_mnemonic (_("CONFIRMER"));
  gtk_widget_show (button_confirmer_supprission_capteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed7), button_confirmer_supprission_capteur_dhia, 728, 672);
  gtk_widget_set_size_request (button_confirmer_supprission_capteur_dhia, 280, 88);

  image13 = create_pixmap (window_supprission_capteur_dhia, "bob-the-builder-logo-00E9291050-seeklogo.com.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed7), image13, 1624, 0);
  gtk_widget_set_size_request (image13, 208, 304);

  label26 = gtk_label_new (_("REF\303\211RENCE"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 600, 368);
  gtk_widget_set_size_request (label26, 176, 64);

  label_output_message_supprission = gtk_label_new ("");
  gtk_widget_show (label_output_message_supprission);
  gtk_fixed_put (GTK_FIXED (fixed7), label_output_message_supprission, 544, 512);
  gtk_widget_set_size_request (label_output_message_supprission, 1016, 104);

  g_signal_connect ((gpointer) button_confirmer_supprission_capteur_dhia, "clicked",
                    G_CALLBACK (on_button_confirmer_supprission_capteur_dhia_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_supprission_capteur_dhia, window_supprission_capteur_dhia, "window_supprission_capteur_dhia");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, image12, "image12");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, label25, "label25");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, entry_ref_capteur_supprission, "entry_ref_capteur_supprission");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, button_confirmer_supprission_capteur_dhia, "button_confirmer_supprission_capteur_dhia");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, image13, "image13");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, label26, "label26");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, label_output_message_supprission, "label_output_message_supprission");

  return window_supprission_capteur_dhia;
}

