/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_connexion (void);
GtkWidget* create_ajout_capteur_dhia (void);
GtkWidget* create_supprission_capteur_dhia (void);
GtkWidget* create_capteur (void);
GtkWidget* create_modifier_capteur_noctis2 (void);
GtkWidget* create_affichage_capteur_dhia (void);
GtkWidget* create_Alarmes_dhia (void);
GtkWidget* create_type_alarme (void);
GtkWidget* create_chercher_dhia (void);
GtkWidget* create_fenetre_authentification (void);
GtkWidget* create_fenetre_principale (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_suppression (void);
GtkWidget* create_fenetre_trouve (void);
GtkWidget* create_fenetre_modification (void);
GtkWidget* create_fenetre_nombre (void);
GtkWidget* create_window_agent_gas (void);
GtkWidget* create_window_login_gas (void);
GtkWidget* create_window_afficher_gas (void);
GtkWidget* create_window_rechercher_gas (void);
GtkWidget* create_window_ajouter_gas (void);
GtkWidget* create_window_modifier_gas (void);
GtkWidget* create_window_supprimer_gas (void);
GtkWidget* create_fenetre_affiche_menu (void);
GtkWidget* create_authentification (void);
GtkWidget* create_ajout_un_menu (void);
GtkWidget* create_modification_menu (void);
GtkWidget* create_supprimer_menu (void);
GtkWidget* create_meilleur_menu (void);
GtkWidget* create_meilleur_plat (void);
