/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_connexion (void);
GtkWidget* create_ajout_capteur_dhia (void);
GtkWidget* create_supprission_capteur_dhia (void);
GtkWidget* create_ajout_nouha (void);
GtkWidget* create_Bienvenue_nouha (void);
GtkWidget* create_supprimer_nouha (void);
GtkWidget* create_capteur (void);
GtkWidget* create_modifier_capteur_noctis2 (void);
GtkWidget* create_affichage_capteur_dhia (void);
GtkWidget* create_Alarmes_dhia (void);
GtkWidget* create_type_alarme (void);
GtkWidget* create_chercher_dhia (void);
