/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_accueil2 (void)
{
  GtkWidget *accueil2;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button_gestionfoyer_accueil;
  GtkWidget *button_nutritionniste_accueil;
  GtkWidget *button_inscription_accueil;
  GtkWidget *button_gestioncapteur_accueil;
  GtkWidget *button_gestionstock_acceuil;

  accueil2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (accueil2), _("ACCUEIL"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (accueil2), fixed1);

  label1 = gtk_label_new (_("BIENVENUE"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 200, 32);
  gtk_widget_set_size_request (label1, 320, 64);

  button_gestionfoyer_accueil = gtk_button_new_with_mnemonic (_("GESTION DU FOYER"));
  gtk_widget_show (button_gestionfoyer_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_gestionfoyer_accueil, 32, 360);
  gtk_widget_set_size_request (button_gestionfoyer_accueil, 168, 64);

  button_nutritionniste_accueil = gtk_button_new_with_mnemonic (_("NUTRITIONISTE"));
  gtk_widget_show (button_nutritionniste_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_nutritionniste_accueil, 512, 176);
  gtk_widget_set_size_request (button_nutritionniste_accueil, 200, 64);

  button_inscription_accueil = gtk_button_new_with_mnemonic (_("INSCRIPTION/LOGIN"));
  gtk_widget_show (button_inscription_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_inscription_accueil, 256, 256);
  gtk_widget_set_size_request (button_inscription_accueil, 200, 72);

  button_gestioncapteur_accueil = gtk_button_new_with_mnemonic (_("GESTION DES CAPTEURS"));
  gtk_widget_show (button_gestioncapteur_accueil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_gestioncapteur_accueil, 512, 360);
  gtk_widget_set_size_request (button_gestioncapteur_accueil, 192, 64);

  button_gestionstock_acceuil = gtk_button_new_with_mnemonic (_("GESTION DU STOCK"));
  gtk_widget_show (button_gestionstock_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed1), button_gestionstock_acceuil, 24, 176);
  gtk_widget_set_size_request (button_gestionstock_acceuil, 160, 64);

  g_signal_connect ((gpointer) button_gestionfoyer_accueil, "clicked",
                    G_CALLBACK (on_button_gestionfoyer_accueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_nutritionniste_accueil, "clicked",
                    G_CALLBACK (on_button_nutritionniste_accueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_inscription_accueil, "clicked",
                    G_CALLBACK (on_button_inscription_accueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gestioncapteur_accueil, "clicked",
                    G_CALLBACK (on_button_gestioncapteur_accueil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gestionstock_acceuil, "clicked",
                    G_CALLBACK (on_button_gestionstock_acceuil_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (accueil2, accueil2, "accueil2");
  GLADE_HOOKUP_OBJECT (accueil2, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (accueil2, label1, "label1");
  GLADE_HOOKUP_OBJECT (accueil2, button_gestionfoyer_accueil, "button_gestionfoyer_accueil");
  GLADE_HOOKUP_OBJECT (accueil2, button_nutritionniste_accueil, "button_nutritionniste_accueil");
  GLADE_HOOKUP_OBJECT (accueil2, button_inscription_accueil, "button_inscription_accueil");
  GLADE_HOOKUP_OBJECT (accueil2, button_gestioncapteur_accueil, "button_gestioncapteur_accueil");
  GLADE_HOOKUP_OBJECT (accueil2, button_gestionstock_acceuil, "button_gestionstock_acceuil");

  return accueil2;
}

GtkWidget*
create_connexion (void)
{
  GtkWidget *connexion;
  GtkWidget *fixed2;
  GtkWidget *label2;
  GtkWidget *entry1_login_connexion;
  GtkWidget *labellogin_connexion;
  GtkWidget *label_password_connexion;
  GtkWidget *entry_password_connexion;
  GtkWidget *button_retour_to_accueil_de_connexion;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label5;
  GtkWidget *label_outputdeconnexion;
  GtkWidget *button_connexion_alterne;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label12;

  connexion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (connexion), _("CONNEXION"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (connexion), fixed2);

  label2 = gtk_label_new (_("Bienvenue \303\240 l'espace connexion"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 216, 0);
  gtk_widget_set_size_request (label2, 368, 48);

  entry1_login_connexion = gtk_entry_new ();
  gtk_widget_show (entry1_login_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_login_connexion, 352, 120);
  gtk_widget_set_size_request (entry1_login_connexion, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_login_connexion), 8226);

  labellogin_connexion = gtk_label_new (_("login"));
  gtk_widget_show (labellogin_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), labellogin_connexion, 176, 120);
  gtk_widget_set_size_request (labellogin_connexion, 136, 32);

  label_password_connexion = gtk_label_new (_("Password"));
  gtk_widget_show (label_password_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), label_password_connexion, 192, 200);
  gtk_widget_set_size_request (label_password_connexion, 128, 40);

  entry_password_connexion = gtk_entry_new ();
  gtk_widget_show (entry_password_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_password_connexion, 352, 208);
  gtk_widget_set_size_request (entry_password_connexion, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_password_connexion), 8226);

  button_retour_to_accueil_de_connexion = gtk_button_new ();
  gtk_widget_show (button_retour_to_accueil_de_connexion);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retour_to_accueil_de_connexion, 0, 456);
  gtk_widget_set_size_request (button_retour_to_accueil_de_connexion, 272, 80);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_retour_to_accueil_de_connexion), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Retour \303\240 l'accueil"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  label_outputdeconnexion = gtk_label_new ("");
  gtk_widget_show (label_outputdeconnexion);
  gtk_fixed_put (GTK_FIXED (fixed2), label_outputdeconnexion, 208, 400);
  gtk_widget_set_size_request (label_outputdeconnexion, 552, 72);

  button_connexion_alterne = gtk_button_new ();
  gtk_widget_show (button_connexion_alterne);
  gtk_fixed_put (GTK_FIXED (fixed2), button_connexion_alterne, 280, 320);
  gtk_widget_set_size_request (button_connexion_alterne, 280, 72);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_connexion_alterne), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("CONNEXION"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox7), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_retour_to_accueil_de_connexion, "clicked",
                    G_CALLBACK (on_button_retour_to_accueil_de_connexion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_connexion_alterne, "clicked",
                    G_CALLBACK (on_button_connexion_alterne_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (connexion, connexion, "connexion");
  GLADE_HOOKUP_OBJECT (connexion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (connexion, label2, "label2");
  GLADE_HOOKUP_OBJECT (connexion, entry1_login_connexion, "entry1_login_connexion");
  GLADE_HOOKUP_OBJECT (connexion, labellogin_connexion, "labellogin_connexion");
  GLADE_HOOKUP_OBJECT (connexion, label_password_connexion, "label_password_connexion");
  GLADE_HOOKUP_OBJECT (connexion, entry_password_connexion, "entry_password_connexion");
  GLADE_HOOKUP_OBJECT (connexion, button_retour_to_accueil_de_connexion, "button_retour_to_accueil_de_connexion");
  GLADE_HOOKUP_OBJECT (connexion, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (connexion, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (connexion, image3, "image3");
  GLADE_HOOKUP_OBJECT (connexion, label5, "label5");
  GLADE_HOOKUP_OBJECT (connexion, label_outputdeconnexion, "label_outputdeconnexion");
  GLADE_HOOKUP_OBJECT (connexion, button_connexion_alterne, "button_connexion_alterne");
  GLADE_HOOKUP_OBJECT (connexion, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (connexion, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (connexion, image7, "image7");
  GLADE_HOOKUP_OBJECT (connexion, label12, "label12");

  return connexion;
}

GtkWidget*
create_accueil0 (void)
{
  GtkWidget *accueil0;
  GtkWidget *fixed4;
  GtkWidget *button_authentification0;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label15;
  GtkWidget *button_incription0;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label14;
  GtkWidget *label_intro;

  accueil0 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (accueil0), _("ACCUEIL0"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (accueil0), fixed4);

  button_authentification0 = gtk_button_new ();
  gtk_widget_show (button_authentification0);
  gtk_fixed_put (GTK_FIXED (fixed4), button_authentification0, 408, 384);
  gtk_widget_set_size_request (button_authentification0, 264, 72);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_authentification0), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("VOUS AVEZ D\303\211JA UN COMPTE?\nCONNECTEZ VOUS !"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox9), label15, FALSE, FALSE, 0);

  button_incription0 = gtk_button_new ();
  gtk_widget_show (button_incription0);
  gtk_fixed_put (GTK_FIXED (fixed4), button_incription0, 8, 384);
  gtk_widget_set_size_request (button_incription0, 280, 72);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_incription0), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("S'INSCRIRE"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);

  label_intro = gtk_label_new (_("BIENVENUE \"INSERT PROJJECT NAME HERE\""));
  gtk_widget_show (label_intro);
  gtk_fixed_put (GTK_FIXED (fixed4), label_intro, 144, 152);
  gtk_widget_set_size_request (label_intro, 416, 104);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (accueil0, accueil0, "accueil0");
  GLADE_HOOKUP_OBJECT (accueil0, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (accueil0, button_authentification0, "button_authentification0");
  GLADE_HOOKUP_OBJECT (accueil0, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (accueil0, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (accueil0, image9, "image9");
  GLADE_HOOKUP_OBJECT (accueil0, label15, "label15");
  GLADE_HOOKUP_OBJECT (accueil0, button_incription0, "button_incription0");
  GLADE_HOOKUP_OBJECT (accueil0, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (accueil0, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (accueil0, image8, "image8");
  GLADE_HOOKUP_OBJECT (accueil0, label14, "label14");
  GLADE_HOOKUP_OBJECT (accueil0, label_intro, "label_intro");

  return accueil0;
}

GtkWidget*
create_window_ajout_capteur_dhia (void)
{
  GtkWidget *window_ajout_capteur_dhia;
  GtkWidget *fixed5;
  GtkWidget *fixed6;
  GtkWidget *image10;
  GtkWidget *entry_nomcapt_dhia;
  GtkWidget *entry_refcapt_dhia;
  GtkWidget *entry_marquecapt_dhia;
  GtkWidget *label16;
  GtkWidget *image11;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *entry_gar_dhia;
  GtkWidget *entry_valmax_dhia;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *entry_valmin_dhia;
  GtkWidget *label23;
  GtkObject *spinbutton_j1_dhia_adj;
  GtkWidget *spinbutton_j1_dhia;
  GtkObject *spinbutton_m1_dhia_adj;
  GtkWidget *spinbutton_m1_dhia;
  GtkObject *spinbutton_a1_dhia_adj;
  GtkWidget *spinbutton_a1_dhia;
  GtkWidget *label24;
  GtkWidget *radiobutton_temp_dhia;
  GSList *radiobutton_temp_dhia_group = NULL;
  GtkWidget *radiobutton_fum__e_dhia;
  GtkWidget *radiobutton_infrarouge_dhia;
  GtkWidget *button_ajoutcapt_interface_dhia;

  window_ajout_capteur_dhia = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_ajout_capteur_dhia), _("Ajout d'un capteur"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window_ajout_capteur_dhia), fixed5);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed5), fixed6, 224, 112);
  gtk_widget_set_size_request (fixed6, 50, 50);

  image10 = create_pixmap (window_ajout_capteur_dhia, "bob-the-builder-logo-00E9291050-seeklogo.com.png");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed5), image10, 1456, 0);
  gtk_widget_set_size_request (image10, 240, 304);

  entry_nomcapt_dhia = gtk_entry_new ();
  gtk_widget_show (entry_nomcapt_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_nomcapt_dhia, 768, 240);
  gtk_widget_set_size_request (entry_nomcapt_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nomcapt_dhia), 8226);

  entry_refcapt_dhia = gtk_entry_new ();
  gtk_widget_show (entry_refcapt_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_refcapt_dhia, 768, 328);
  gtk_widget_set_size_request (entry_refcapt_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_refcapt_dhia), 8226);

  entry_marquecapt_dhia = gtk_entry_new ();
  gtk_widget_show (entry_marquecapt_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_marquecapt_dhia, 768, 368);
  gtk_widget_set_size_request (entry_marquecapt_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_marquecapt_dhia), 8226);

  label16 = gtk_label_new (_("AJOUTER UN CAPTEUR"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 720, 120);
  gtk_widget_set_size_request (label16, 416, 104);

  image11 = create_pixmap (window_ajout_capteur_dhia, "Logo_ESPRIT_-_Tunisie.png");
  gtk_widget_show (image11);
  gtk_fixed_put (GTK_FIXED (fixed5), image11, 0, 0);
  gtk_widget_set_size_request (image11, 680, 248);

  label17 = gtk_label_new (_("REFERENCE"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed5), label17, 576, 336);
  gtk_widget_set_size_request (label17, 88, 16);

  label18 = gtk_label_new (_("MARQUE"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed5), label18, 552, 376);
  gtk_widget_set_size_request (label18, 120, 16);

  label19 = gtk_label_new (_("TYPE DE CAPTEUR"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 568, 416);
  gtk_widget_set_size_request (label19, 144, 25);

  label20 = gtk_label_new (_("GARANTIE"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 544, 472);
  gtk_widget_set_size_request (label20, 144, 32);

  entry_gar_dhia = gtk_entry_new ();
  gtk_widget_show (entry_gar_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_gar_dhia, 768, 472);
  gtk_widget_set_size_request (entry_gar_dhia, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_gar_dhia), 8226);

  entry_valmax_dhia = gtk_entry_new ();
  gtk_widget_show (entry_valmax_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_valmax_dhia, 768, 520);
  gtk_widget_set_size_request (entry_valmax_dhia, 56, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmax_dhia), 8226);

  label21 = gtk_label_new (_("VALEUR\nMAXIMALE"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 584, 520);
  gtk_widget_set_size_request (label21, 80, 32);

  label22 = gtk_label_new (_("VALEUR\nMINIMALE"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 576, 560);
  gtk_widget_set_size_request (label22, 88, 48);

  entry_valmin_dhia = gtk_entry_new ();
  gtk_widget_show (entry_valmin_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_valmin_dhia, 768, 568);
  gtk_widget_set_size_request (entry_valmin_dhia, 56, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmin_dhia), 8226);

  label23 = gtk_label_new (_("NOM DU CAPTEUR"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 576, 248);
  gtk_widget_set_size_request (label23, 136, 17);

  spinbutton_j1_dhia_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_j1_dhia = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_j1_dhia_adj), 1, 0);
  gtk_widget_show (spinbutton_j1_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_j1_dhia, 768, 280);
  gtk_widget_set_size_request (spinbutton_j1_dhia, 60, 27);

  spinbutton_m1_dhia_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_m1_dhia = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_m1_dhia_adj), 1, 0);
  gtk_widget_show (spinbutton_m1_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_m1_dhia, 856, 280);
  gtk_widget_set_size_request (spinbutton_m1_dhia, 60, 27);

  spinbutton_a1_dhia_adj = gtk_adjustment_new (1999, 1999, 2050, 1, 10, 10);
  spinbutton_a1_dhia = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_a1_dhia_adj), 1, 0);
  gtk_widget_show (spinbutton_a1_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton_a1_dhia, 952, 280);
  gtk_widget_set_size_request (spinbutton_a1_dhia, 60, 27);

  label24 = gtk_label_new (_("DATE"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 584, 288);
  gtk_widget_set_size_request (label24, 80, 16);

  radiobutton_temp_dhia = gtk_radio_button_new_with_mnemonic (NULL, _("DE \nTEMPERATURE"));
  gtk_widget_show (radiobutton_temp_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_temp_dhia, 752, 408);
  gtk_widget_set_size_request (radiobutton_temp_dhia, 128, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_temp_dhia), radiobutton_temp_dhia_group);
  radiobutton_temp_dhia_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_temp_dhia));

  radiobutton_fum__e_dhia = gtk_radio_button_new_with_mnemonic (NULL, _("DE FUM\303\211E"));
  gtk_widget_show (radiobutton_fum__e_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_fum__e_dhia, 904, 416);
  gtk_widget_set_size_request (radiobutton_fum__e_dhia, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_fum__e_dhia), radiobutton_temp_dhia_group);
  radiobutton_temp_dhia_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_fum__e_dhia));

  radiobutton_infrarouge_dhia = gtk_radio_button_new_with_mnemonic (NULL, _("INFRAROUGE\n(DE MOUVEMENT)"));
  gtk_widget_show (radiobutton_infrarouge_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_infrarouge_dhia, 1016, 400);
  gtk_widget_set_size_request (radiobutton_infrarouge_dhia, 152, 56);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_infrarouge_dhia), radiobutton_temp_dhia_group);
  radiobutton_temp_dhia_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_infrarouge_dhia));

  button_ajoutcapt_interface_dhia = gtk_button_new_with_mnemonic (_("CONFIRMER"));
  gtk_widget_show (button_ajoutcapt_interface_dhia);
  gtk_fixed_put (GTK_FIXED (fixed5), button_ajoutcapt_interface_dhia, 704, 712);
  gtk_widget_set_size_request (button_ajoutcapt_interface_dhia, 440, 112);

  g_signal_connect ((gpointer) radiobutton_temp_dhia, "toggled",
                    G_CALLBACK (on_radiobutton_temp_dhia_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_fum__e_dhia, "toggled",
                    G_CALLBACK (on_radiobutton_fum__e_dhia_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_infrarouge_dhia, "toggled",
                    G_CALLBACK (on_radiobutton_infrarouge_dhia_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajoutcapt_interface_dhia, "clicked",
                    G_CALLBACK (on_button_ajoutcapt_interface_dhia_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajout_capteur_dhia, window_ajout_capteur_dhia, "window_ajout_capteur_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_nomcapt_dhia, "entry_nomcapt_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_refcapt_dhia, "entry_refcapt_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_marquecapt_dhia, "entry_marquecapt_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label18, "label18");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_gar_dhia, "entry_gar_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_valmax_dhia, "entry_valmax_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label21, "label21");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label22, "label22");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, entry_valmin_dhia, "entry_valmin_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label23, "label23");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, spinbutton_j1_dhia, "spinbutton_j1_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, spinbutton_m1_dhia, "spinbutton_m1_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, spinbutton_a1_dhia, "spinbutton_a1_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, label24, "label24");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, radiobutton_temp_dhia, "radiobutton_temp_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, radiobutton_fum__e_dhia, "radiobutton_fum__e_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, radiobutton_infrarouge_dhia, "radiobutton_infrarouge_dhia");
  GLADE_HOOKUP_OBJECT (window_ajout_capteur_dhia, button_ajoutcapt_interface_dhia, "button_ajoutcapt_interface_dhia");

  return window_ajout_capteur_dhia;
}

GtkWidget*
create_window_supprission_capteur_dhia (void)
{
  GtkWidget *window_supprission_capteur_dhia;
  GtkWidget *fixed7;
  GtkWidget *image12;
  GtkWidget *label25;
  GtkWidget *entry_ref_capteur_supprission;
  GtkWidget *button_confirmer_supprission_capteur_dhia;
  GtkWidget *image13;
  GtkWidget *label26;
  GtkWidget *label_output_message_supprission;

  window_supprission_capteur_dhia = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_supprission_capteur_dhia), _("supprission d'un capteur"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window_supprission_capteur_dhia), fixed7);

  image12 = create_pixmap (window_supprission_capteur_dhia, "Logo_ESPRIT_-_Tunisie.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed7), image12, 0, 0);
  gtk_widget_set_size_request (image12, 504, 248);

  label25 = gtk_label_new (_("SUPPRESSION D'UN CAPTEUR"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 792, 168);
  gtk_widget_set_size_request (label25, 360, 96);

  entry_ref_capteur_supprission = gtk_entry_new ();
  gtk_widget_show (entry_ref_capteur_supprission);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_ref_capteur_supprission, 824, 384);
  gtk_widget_set_size_request (entry_ref_capteur_supprission, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ref_capteur_supprission), 8226);

  button_confirmer_supprission_capteur_dhia = gtk_button_new_with_mnemonic (_("CONFIRMER"));
  gtk_widget_show (button_confirmer_supprission_capteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed7), button_confirmer_supprission_capteur_dhia, 728, 672);
  gtk_widget_set_size_request (button_confirmer_supprission_capteur_dhia, 280, 88);

  image13 = create_pixmap (window_supprission_capteur_dhia, "bob-the-builder-logo-00E9291050-seeklogo.com.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed7), image13, 1624, 0);
  gtk_widget_set_size_request (image13, 208, 304);

  label26 = gtk_label_new (_("REF\303\211RENCE"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 600, 368);
  gtk_widget_set_size_request (label26, 176, 64);

  label_output_message_supprission = gtk_label_new ("");
  gtk_widget_show (label_output_message_supprission);
  gtk_fixed_put (GTK_FIXED (fixed7), label_output_message_supprission, 544, 512);
  gtk_widget_set_size_request (label_output_message_supprission, 1016, 104);

  g_signal_connect ((gpointer) button_confirmer_supprission_capteur_dhia, "clicked",
                    G_CALLBACK (on_button_confirmer_supprission_capteur_dhia_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_supprission_capteur_dhia, window_supprission_capteur_dhia, "window_supprission_capteur_dhia");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, image12, "image12");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, label25, "label25");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, entry_ref_capteur_supprission, "entry_ref_capteur_supprission");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, button_confirmer_supprission_capteur_dhia, "button_confirmer_supprission_capteur_dhia");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, image13, "image13");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, label26, "label26");
  GLADE_HOOKUP_OBJECT (window_supprission_capteur_dhia, label_output_message_supprission, "label_output_message_supprission");

  return window_supprission_capteur_dhia;
}

GtkWidget*
create_ajout_nouha (void)
{
  GtkWidget *ajout_nouha;
  GtkWidget *fixed8;
  GtkWidget *entry_id1;
  GtkWidget *entry_n;
  GtkWidget *entry_m;
  GtkWidget *entry_q;
  GtkWidget *label27;
  GtkObject *journouha_adj;
  GtkWidget *journouha;
  GtkObject *moisnouha_adj;
  GtkWidget *moisnouha;
  GtkObject *anneenouha_adj;
  GtkWidget *anneenouha;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *image14;
  GtkWidget *button_annuler_nouha;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image15;
  GtkWidget *label36;
  GtkWidget *button_valider_nouha;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image16;
  GtkWidget *label37;
  GtkWidget *comboboxnouha;

  ajout_nouha = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajout_nouha), _("ajout"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (ajout_nouha), fixed8);

  entry_id1 = gtk_entry_new ();
  gtk_widget_show (entry_id1);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_id1, 128, 168);
  gtk_widget_set_size_request (entry_id1, 120, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id1), 8226);

  entry_n = gtk_entry_new ();
  gtk_widget_show (entry_n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_n, 376, 168);
  gtk_widget_set_size_request (entry_n, 120, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_n), 8226);

  entry_m = gtk_entry_new ();
  gtk_widget_show (entry_m);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_m, 128, 224);
  gtk_widget_set_size_request (entry_m, 120, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_m), 8226);

  entry_q = gtk_entry_new ();
  gtk_widget_show (entry_q);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_q, 376, 224);
  gtk_widget_set_size_request (entry_q, 120, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_q), 8226);

  label27 = gtk_label_new (_("Categorie:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed8), label27, 16, 288);
  gtk_widget_set_size_request (label27, 88, 32);

  journouha_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 10);
  journouha = gtk_spin_button_new (GTK_ADJUSTMENT (journouha_adj), 1, 0);
  gtk_widget_show (journouha);
  gtk_fixed_put (GTK_FIXED (fixed8), journouha, 168, 368);
  gtk_widget_set_size_request (journouha, 60, 27);

  moisnouha_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 10);
  moisnouha = gtk_spin_button_new (GTK_ADJUSTMENT (moisnouha_adj), 1, 0);
  gtk_widget_show (moisnouha);
  gtk_fixed_put (GTK_FIXED (fixed8), moisnouha, 288, 368);
  gtk_widget_set_size_request (moisnouha, 60, 27);

  anneenouha_adj = gtk_adjustment_new (0, 2020, 2030, 1, 10, 10);
  anneenouha = gtk_spin_button_new (GTK_ADJUSTMENT (anneenouha_adj), 1, 0);
  gtk_widget_show (anneenouha);
  gtk_fixed_put (GTK_FIXED (fixed8), anneenouha, 416, 368);
  gtk_widget_set_size_request (anneenouha, 60, 27);

  label28 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed8), label28, 16, 168);
  gtk_widget_set_size_request (label28, 112, 32);

  label29 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed8), label29, 280, 168);
  gtk_widget_set_size_request (label29, 96, 32);

  label30 = gtk_label_new (_("Marque:"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed8), label30, 24, 224);
  gtk_widget_set_size_request (label30, 88, 32);

  label31 = gtk_label_new (_("Quantit\303\251:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 296, 224);
  gtk_widget_set_size_request (label31, 72, 32);

  label32 = gtk_label_new (_("Date de \nfabrication:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed8), label32, 8, 344);
  gtk_widget_set_size_request (label32, 112, 56);

  label33 = gtk_label_new (_("Jour"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed8), label33, 120, 368);
  gtk_widget_set_size_request (label33, 48, 24);

  label34 = gtk_label_new (_("Mois"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed8), label34, 232, 368);
  gtk_widget_set_size_request (label34, 56, 24);

  label35 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed8), label35, 360, 368);
  gtk_widget_set_size_request (label35, 48, 24);

  image14 = create_pixmap (ajout_nouha, "download.jfif");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed8), image14, 0, 0);
  gtk_widget_set_size_request (image14, 520, 112);

  button_annuler_nouha = gtk_button_new ();
  gtk_widget_show (button_annuler_nouha);
  gtk_fixed_put (GTK_FIXED (fixed8), button_annuler_nouha, 120, 448);
  gtk_widget_set_size_request (button_annuler_nouha, 88, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_annuler_nouha), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox10), image15, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox10), label36, FALSE, FALSE, 0);

  button_valider_nouha = gtk_button_new ();
  gtk_widget_show (button_valider_nouha);
  gtk_fixed_put (GTK_FIXED (fixed8), button_valider_nouha, 320, 448);
  gtk_widget_set_size_request (button_valider_nouha, 80, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_valider_nouha), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image16 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox11), image16, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox11), label37, FALSE, FALSE, 0);

  comboboxnouha = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxnouha);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxnouha, 128, 288);
  gtk_widget_set_size_request (comboboxnouha, 120, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnouha), _("viandes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnouha), _("poissons"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnouha), _("\305\223ufs"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnouha), _("laitiers"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnouha), _("l\303\251gumes et fruits"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnouha), _("pates"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxnouha), _("boissons"));

  g_signal_connect ((gpointer) button_annuler_nouha, "clicked",
                    G_CALLBACK (on_button_annuler_nouha_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_valider_nouha, "clicked",
                    G_CALLBACK (on_button_valider_nouha_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_nouha, ajout_nouha, "ajout_nouha");
  GLADE_HOOKUP_OBJECT (ajout_nouha, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (ajout_nouha, entry_id1, "entry_id1");
  GLADE_HOOKUP_OBJECT (ajout_nouha, entry_n, "entry_n");
  GLADE_HOOKUP_OBJECT (ajout_nouha, entry_m, "entry_m");
  GLADE_HOOKUP_OBJECT (ajout_nouha, entry_q, "entry_q");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajout_nouha, journouha, "journouha");
  GLADE_HOOKUP_OBJECT (ajout_nouha, moisnouha, "moisnouha");
  GLADE_HOOKUP_OBJECT (ajout_nouha, anneenouha, "anneenouha");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label28, "label28");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label29, "label29");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label31, "label31");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label32, "label32");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label33, "label33");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label34, "label34");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label35, "label35");
  GLADE_HOOKUP_OBJECT (ajout_nouha, image14, "image14");
  GLADE_HOOKUP_OBJECT (ajout_nouha, button_annuler_nouha, "button_annuler_nouha");
  GLADE_HOOKUP_OBJECT (ajout_nouha, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ajout_nouha, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ajout_nouha, image15, "image15");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label36, "label36");
  GLADE_HOOKUP_OBJECT (ajout_nouha, button_valider_nouha, "button_valider_nouha");
  GLADE_HOOKUP_OBJECT (ajout_nouha, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ajout_nouha, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ajout_nouha, image16, "image16");
  GLADE_HOOKUP_OBJECT (ajout_nouha, label37, "label37");
  GLADE_HOOKUP_OBJECT (ajout_nouha, comboboxnouha, "comboboxnouha");

  return ajout_nouha;
}

GtkWidget*
create_Bienvenue_nouha (void)
{
  GtkWidget *Bienvenue_nouha;
  GtkWidget *fixed9;
  GtkWidget *label38;
  GtkWidget *image17;
  GtkWidget *button_Bienvenue_stock;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image18;
  GtkWidget *label39;
  GtkWidget *radiobutton_ajout;
  GSList *radiobutton_ajout_group = NULL;
  GtkWidget *radiobutton_modif;
  GtkWidget *radiobutton_supp;
  GtkWidget *radiobutton_cherch;
  GtkWidget *radiobutton_affichier;
  GtkWidget *radiobutton_affichunique;

  Bienvenue_nouha = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Bienvenue_nouha), _("Bienvenue"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Bienvenue_nouha), fixed9);

  label38 = gtk_label_new_with_mnemonic (_("voulez-vous choisir votre tache:"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed9), label38, 16, 120);
  gtk_widget_set_size_request (label38, 272, 32);
  gtk_label_set_justify (GTK_LABEL (label38), GTK_JUSTIFY_RIGHT);
  gtk_label_set_width_chars (GTK_LABEL (label38), 0);

  image17 = create_pixmap (Bienvenue_nouha, "download.jfif");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed9), image17, 0, 0);
  gtk_widget_set_size_request (image17, 520, 120);

  button_Bienvenue_stock = gtk_button_new ();
  gtk_widget_show (button_Bienvenue_stock);
  gtk_fixed_put (GTK_FIXED (fixed9), button_Bienvenue_stock, 168, 424);
  gtk_widget_set_size_request (button_Bienvenue_stock, 168, 56);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_Bienvenue_stock), alignment12);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment12), 0, 0, 0, 4);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox12), image18, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Suivant"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox12), label39, FALSE, FALSE, 0);

  radiobutton_ajout = gtk_radio_button_new_with_mnemonic (NULL, _("Ajouter un ou des produits"));
  gtk_widget_show (radiobutton_ajout);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_ajout, 88, 160);
  gtk_widget_set_size_request (radiobutton_ajout, 216, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_ajout), radiobutton_ajout_group);
  radiobutton_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_ajout));

  radiobutton_modif = gtk_radio_button_new_with_mnemonic (NULL, _("Modifier un produit"));
  gtk_widget_show (radiobutton_modif);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_modif, 88, 200);
  gtk_widget_set_size_request (radiobutton_modif, 216, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_modif), radiobutton_ajout_group);
  radiobutton_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_modif));

  radiobutton_supp = gtk_radio_button_new_with_mnemonic (NULL, _("Supprimer un produit"));
  gtk_widget_show (radiobutton_supp);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_supp, 88, 240);
  gtk_widget_set_size_request (radiobutton_supp, 232, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_supp), radiobutton_ajout_group);
  radiobutton_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_supp));

  radiobutton_cherch = gtk_radio_button_new_with_mnemonic (NULL, _("Chercher un produit"));
  gtk_widget_show (radiobutton_cherch);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_cherch, 88, 280);
  gtk_widget_set_size_request (radiobutton_cherch, 232, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_cherch), radiobutton_ajout_group);
  radiobutton_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_cherch));

  radiobutton_affichier = gtk_radio_button_new_with_mnemonic (NULL, _("Afficher tous les produits"));
  gtk_widget_show (radiobutton_affichier);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_affichier, 88, 320);
  gtk_widget_set_size_request (radiobutton_affichier, 240, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_affichier), radiobutton_ajout_group);
  radiobutton_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_affichier));

  radiobutton_affichunique = gtk_radio_button_new_with_mnemonic (NULL, _("Afficher uniquement  les produits \nen rupture de stock"));
  gtk_widget_show (radiobutton_affichunique);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_affichunique, 88, 360);
  gtk_widget_set_size_request (radiobutton_affichunique, 264, 48);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_affichunique), radiobutton_ajout_group);
  radiobutton_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_affichunique));

  g_signal_connect ((gpointer) button_Bienvenue_stock, "clicked",
                    G_CALLBACK (on_button_Bienvenue_stock_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_ajout, "toggled",
                    G_CALLBACK (on_radiobutton_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_modif, "toggled",
                    G_CALLBACK (on_radiobutton_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_supp, "toggled",
                    G_CALLBACK (on_radiobutton_supp_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_cherch, "toggled",
                    G_CALLBACK (on_radiobutton_cherch_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_affichier, "toggled",
                    G_CALLBACK (on_radiobutton_affichier_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_affichunique, "toggled",
                    G_CALLBACK (on_radiobutton_affichunique_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Bienvenue_nouha, Bienvenue_nouha, "Bienvenue_nouha");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, label38, "label38");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, image17, "image17");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, button_Bienvenue_stock, "button_Bienvenue_stock");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, image18, "image18");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, label39, "label39");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, radiobutton_ajout, "radiobutton_ajout");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, radiobutton_modif, "radiobutton_modif");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, radiobutton_supp, "radiobutton_supp");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, radiobutton_cherch, "radiobutton_cherch");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, radiobutton_affichier, "radiobutton_affichier");
  GLADE_HOOKUP_OBJECT (Bienvenue_nouha, radiobutton_affichunique, "radiobutton_affichunique");

  return Bienvenue_nouha;
}

GtkWidget*
create_supprimer_nouha (void)
{
  GtkWidget *supprimer_nouha;
  GtkWidget *fixed10;
  GtkWidget *entrysuppnouha;
  GtkWidget *label40;
  GtkWidget *image19;
  GtkWidget *button_retour_nouha;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image21;
  GtkWidget *label43;
  GtkWidget *button_supprimer_nouha;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image20;
  GtkWidget *label41;
  GtkWidget *yesorno;

  supprimer_nouha = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_nouha), _("suppression"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (supprimer_nouha), fixed10);

  entrysuppnouha = gtk_entry_new ();
  gtk_widget_show (entrysuppnouha);
  gtk_fixed_put (GTK_FIXED (fixed10), entrysuppnouha, 184, 144);
  gtk_widget_set_size_request (entrysuppnouha, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysuppnouha), 8226);

  label40 = gtk_label_new (_("Donnez l'identifiant:"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed10), label40, 16, 144);
  gtk_widget_set_size_request (label40, 168, 32);

  image19 = create_pixmap (supprimer_nouha, "download.jfif");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed10), image19, 0, 0);
  gtk_widget_set_size_request (image19, 520, 120);

  button_retour_nouha = gtk_button_new ();
  gtk_widget_show (button_retour_nouha);
  gtk_fixed_put (GTK_FIXED (fixed10), button_retour_nouha, 208, 344);
  gtk_widget_set_size_request (button_retour_nouha, 128, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_retour_nouha), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image21 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox14), image21, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox14), label43, FALSE, FALSE, 0);

  button_supprimer_nouha = gtk_button_new ();
  gtk_widget_show (button_supprimer_nouha);
  gtk_fixed_put (GTK_FIXED (fixed10), button_supprimer_nouha, 208, 208);
  gtk_widget_set_size_request (button_supprimer_nouha, 120, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_supprimer_nouha), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image20 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox13), image20, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, FALSE, FALSE, 0);

  yesorno = gtk_label_new ("");
  gtk_widget_show (yesorno);
  gtk_fixed_put (GTK_FIXED (fixed10), yesorno, 128, 272);
  gtk_widget_set_size_request (yesorno, 280, 64);

  g_signal_connect ((gpointer) button_retour_nouha, "clicked",
                    G_CALLBACK (on_button_retour_nouha_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_nouha, "clicked",
                    G_CALLBACK (on_button_supprimer_nouha_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_nouha, supprimer_nouha, "supprimer_nouha");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, entrysuppnouha, "entrysuppnouha");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, label40, "label40");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, image19, "image19");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, button_retour_nouha, "button_retour_nouha");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, image21, "image21");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, label43, "label43");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, button_supprimer_nouha, "button_supprimer_nouha");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, image20, "image20");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, label41, "label41");
  GLADE_HOOKUP_OBJECT (supprimer_nouha, yesorno, "yesorno");

  return supprimer_nouha;
}

GtkWidget*
create_capteur (void)
{
  GtkWidget *capteur;
  GtkWidget *fixed11;
  GtkWidget *image22;
  GtkWidget *hseparator1;
  GtkWidget *vseparator2;
  GtkWidget *hseparator2;
  GtkWidget *hseparator3;
  GtkWidget *vseparator3;
  GtkWidget *vseparator4;
  GtkWidget *vseparator1;
  GtkWidget *button_ajout_capteur_dhia;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image25;
  GtkWidget *label46;
  GtkWidget *button_retourto_accueil_from_capteur;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image29;
  GtkWidget *label50;
  GtkWidget *button_supprimercapteur_dhia;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image24;
  GtkWidget *label45;
  GtkWidget *button_modifiercapteur_dhia;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image23;
  GtkWidget *label44;
  GtkWidget *button_cherchercapteur_dhia;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image26;
  GtkWidget *label47;
  GtkWidget *button_affichiercapteur_dhia;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image27;
  GtkWidget *label48;

  capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (capteur), _("ACCUEIL"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (capteur), fixed11);

  image22 = create_pixmap (capteur, "df.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed11), image22, 344, 216);
  gtk_widget_set_size_request (image22, 184, 160);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed11), hseparator1, 544, 280);
  gtk_widget_set_size_request (hseparator1, 112, 24);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed11), vseparator2, 424, 384);
  gtk_widget_set_size_request (vseparator2, 32, 80);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed11), hseparator2, 224, 272);
  gtk_widget_set_size_request (hseparator2, 112, 32);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed11), hseparator3, 120, 280);
  gtk_widget_set_size_request (hseparator3, 104, 16);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_fixed_put (GTK_FIXED (fixed11), vseparator3, 112, 176);
  gtk_widget_set_size_request (vseparator3, 24, 112);

  vseparator4 = gtk_vseparator_new ();
  gtk_widget_show (vseparator4);
  gtk_fixed_put (GTK_FIXED (fixed11), vseparator4, 120, 288);
  gtk_widget_set_size_request (vseparator4, 16, 104);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed11), vseparator1, 400, 96);
  gtk_widget_set_size_request (vseparator1, 72, 112);

  button_ajout_capteur_dhia = gtk_button_new ();
  gtk_widget_show (button_ajout_capteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed11), button_ajout_capteur_dhia, 336, 32);
  gtk_widget_set_size_request (button_ajout_capteur_dhia, 208, 64);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_ajout_capteur_dhia), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image25 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox17), image25, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("AJOUT DE CAPTEUR"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox17), label46, FALSE, FALSE, 0);

  button_retourto_accueil_from_capteur = gtk_button_new ();
  gtk_widget_show (button_retourto_accueil_from_capteur);
  gtk_fixed_put (GTK_FIXED (fixed11), button_retourto_accueil_from_capteur, 600, 464);
  gtk_widget_set_size_request (button_retourto_accueil_from_capteur, 264, 80);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_retourto_accueil_from_capteur), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image29 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox21), image29, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Retour \303\240 l'acceuil"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox21), label50, FALSE, FALSE, 0);

  button_supprimercapteur_dhia = gtk_button_new ();
  gtk_widget_show (button_supprimercapteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed11), button_supprimercapteur_dhia, 360, 480);
  gtk_widget_set_size_request (button_supprimercapteur_dhia, 200, 64);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_supprimercapteur_dhia), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image24 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox16), image24, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("SUPPRIMER"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox16), label45, FALSE, FALSE, 0);

  button_modifiercapteur_dhia = gtk_button_new ();
  gtk_widget_show (button_modifiercapteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed11), button_modifiercapteur_dhia, 672, 264);
  gtk_widget_set_size_request (button_modifiercapteur_dhia, 184, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_modifiercapteur_dhia), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image23 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox15), image23, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("MODIFICATION"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox15), label44, FALSE, FALSE, 0);

  button_cherchercapteur_dhia = gtk_button_new ();
  gtk_widget_show (button_cherchercapteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed11), button_cherchercapteur_dhia, 8, 120);
  gtk_widget_set_size_request (button_cherchercapteur_dhia, 200, 56);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_cherchercapteur_dhia), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image26 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox18), image26, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("CHERCHER"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox18), label47, FALSE, FALSE, 0);

  button_affichiercapteur_dhia = gtk_button_new ();
  gtk_widget_show (button_affichiercapteur_dhia);
  gtk_fixed_put (GTK_FIXED (fixed11), button_affichiercapteur_dhia, 16, 392);
  gtk_widget_set_size_request (button_affichiercapteur_dhia, 248, 72);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_affichiercapteur_dhia), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image27 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox19), image27, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("AFFICHAGE"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox19), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ajout_capteur_dhia, "clicked",
                    G_CALLBACK (on_button_ajout_capteur_dhia_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourto_accueil_from_capteur, "clicked",
                    G_CALLBACK (on_button_retourto_accueil_from_capteur_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimercapteur_dhia, "clicked",
                    G_CALLBACK (on_button_supprimercapteur_dhia_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifiercapteur_dhia, "clicked",
                    G_CALLBACK (on_button_modifiercapteur_dhia_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cherchercapteur_dhia, "clicked",
                    G_CALLBACK (on_button_cherchercapteur_dhia_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affichiercapteur_dhia, "clicked",
                    G_CALLBACK (on_button_affichiercapteur_dhia_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (capteur, capteur, "capteur");
  GLADE_HOOKUP_OBJECT (capteur, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (capteur, image22, "image22");
  GLADE_HOOKUP_OBJECT (capteur, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (capteur, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (capteur, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (capteur, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (capteur, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (capteur, vseparator4, "vseparator4");
  GLADE_HOOKUP_OBJECT (capteur, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (capteur, button_ajout_capteur_dhia, "button_ajout_capteur_dhia");
  GLADE_HOOKUP_OBJECT (capteur, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (capteur, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (capteur, image25, "image25");
  GLADE_HOOKUP_OBJECT (capteur, label46, "label46");
  GLADE_HOOKUP_OBJECT (capteur, button_retourto_accueil_from_capteur, "button_retourto_accueil_from_capteur");
  GLADE_HOOKUP_OBJECT (capteur, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (capteur, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (capteur, image29, "image29");
  GLADE_HOOKUP_OBJECT (capteur, label50, "label50");
  GLADE_HOOKUP_OBJECT (capteur, button_supprimercapteur_dhia, "button_supprimercapteur_dhia");
  GLADE_HOOKUP_OBJECT (capteur, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (capteur, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (capteur, image24, "image24");
  GLADE_HOOKUP_OBJECT (capteur, label45, "label45");
  GLADE_HOOKUP_OBJECT (capteur, button_modifiercapteur_dhia, "button_modifiercapteur_dhia");
  GLADE_HOOKUP_OBJECT (capteur, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (capteur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (capteur, image23, "image23");
  GLADE_HOOKUP_OBJECT (capteur, label44, "label44");
  GLADE_HOOKUP_OBJECT (capteur, button_cherchercapteur_dhia, "button_cherchercapteur_dhia");
  GLADE_HOOKUP_OBJECT (capteur, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (capteur, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (capteur, image26, "image26");
  GLADE_HOOKUP_OBJECT (capteur, label47, "label47");
  GLADE_HOOKUP_OBJECT (capteur, button_affichiercapteur_dhia, "button_affichiercapteur_dhia");
  GLADE_HOOKUP_OBJECT (capteur, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (capteur, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (capteur, image27, "image27");
  GLADE_HOOKUP_OBJECT (capteur, label48, "label48");

  return capteur;
}

